# Generated by Django 2.2.5 on 2019-09-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_remove_contact_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default-avatar_tcWonAu_iaqxAtf.png', upload_to=''),
        ),
    ]
